name: Check Bundle Identifier Change Script

on: 
  push:
  pull_request:

jobs:
  build:
    name: Xcode Build
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Project
        run: |
          xcodebuild -project azooKey.xcodeproj \
                     -showBuildSettings
