name: Unity iOS Build

on:
  workflow_dispatch:

jobs:          
  iOS-build:
    name: Generate IPA
    runs-on: macos-latest

    steps:
      - name: Create ExportOptions.plist
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>method</key><string>app-store</string><key>teamID</key><string>ZGQ36244W3</string><key>uploadSymbols</key><true/><key>compileBitcode</key><true/></dict></plist>' > ExportOptions.plist
        
      - name: Build Project
        run: |
          xcodebuild -project azooKey.xcodeproj \
                     -scheme MainApp \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO \
                     build
