name: Unity iOS Build

on:
  push

jobs:          
  iOS-build:
    name: iOS Build
    runs-on: macos-14

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pip
        run: python -m ensurepip --upgrade

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Directory
        run: |
          ./setup.sh

      - name: Build Project
        run: |
          xcodebuild -project azooKey.xcodeproj \
                     -scheme MainApp \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO \
                     build
