# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps: 
    - uses: swift-actions/setup-swift@e1dca7c4a36344146bbc2803f0d538462477bb37
      with:
        swift-version: "5.9"

    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swift-

    - name: Build
      # TODO: add KeyboardViews
      run: swift build --package-path AzooKeyCore --target SwiftUIUtils;swift build --package-path AzooKeyCore --target KeyboardThemes

    - name: Run tests
      run: echo "There is no test suits yet"
