name: Run azooKeyTests

on:
  push

jobs:
  test:
    runs-on: macos-14
    strategy:
      matrix:
        device: [iPhone SE (3rd generation), iPhone 14, iPhone 14 Plus, iPhone 14 Pro, iPhone 14 Pro Max, iPhone 15, iPhone 15 Plus, iPhone 15 Pro, iPhone 15 Pro Max, iPad Air (5th generation), iPad (10th generation), iPad mini (6th generation), iPad Pro (11-inch) (4th generation), iPad Pro (12.9-inch) (6th generation)]
        ios-version: [17.0, 17.2]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: 'refactoring/add_submodule'

    - run : xcrun simctl list

    - name: Run tests
      run: |
        xcodebuild test -project azooKey.xcodeproj \
                        -scheme azooKeyTests \
                        -sdk iphonesimulator \
                        -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios-version }}'
