name: Run azooKeyTests

on:
  push

jobs:
  test:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: 'refactoring/add_submodule'

    - name: Build Project
      run: |
        xcodebuild build -project azooKey.xcodeproj \
                   -scheme MainApp \
                   -sdk iphoneos \
                   -configuration Release \
                   CODE_SIGNING_ALLOWED=NO \

    - name: Run tests
      run: |
        xcodebuild test -project azooKey.xcodeproj \
                        -scheme azooKeyTests \
                        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
