name: Run azooKeyTests

on:
  push

jobs:
  test:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: 'refactoring/add_submodule'

    - run : xcrun simctl list

    - run : xcrun instruments -s

    - name: Run tests
      run: |
        xcodebuild test -project azooKey.xcodeproj \
                        -scheme azooKeyTests \
                        -sdk iphonesimulator \
